// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6KYl3K39mFn-H8xo2zPGfaPPyTSB7_24',
    appId: '1:824033316260:web:1890d2b13b10551eba4531',
    messagingSenderId: '824033316260',
    projectId: 'virtual-dating-189c7',
    authDomain: 'virtual-dating-189c7.firebaseapp.com',
    storageBucket: 'virtual-dating-189c7.firebasestorage.app',
    measurementId: 'G-EF91KF2H8T',
    databaseURL: "https://virtual-dating-189c7-default-rtdb.asia-southeast1.firebasedatabase.app"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq9J3c7wNbMxApAlay3C2g7Sv_0qsnkLo',
    appId: '1:824033316260:android:2fbe016a439e8999ba4531',
    messagingSenderId: '824033316260',
    projectId: 'virtual-dating-189c7',
    storageBucket: 'virtual-dating-189c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_T7GFp-SyxxCkZa0dLbJsvBLM2CKu9TM',
    appId: '1:824033316260:ios:8ffde5b25f084ddbba4531',
    messagingSenderId: '824033316260',
    projectId: 'virtual-dating-189c7',
    storageBucket: 'virtual-dating-189c7.firebasestorage.app',
    iosClientId: '824033316260-a47mbgk7ub68gk9jdqq0hahalg55789n.apps.googleusercontent.com',
    iosBundleId: 'com.example.virtualDating',
  );
}
